### ISSUE TITLE
Error: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by cdfa** [azimuttapp/azimutt#335]
Hi, I just tried azimutt on a local MariaDB instance, but I get:
```
$ npx azimutt@latest explore mariadb://hconductor@localhost:3306/hconductor
Connected to the database, exporting for schema 'hconductor' ...
Found 223 tables ...
Found 1264 columns ...
Found 954 constraint columns ...
Found 6 checks ...
Inferring JSON columns ...
Inferring polymorphic relations ...
✔︎ Exported 223 tables and 276 relations from the database!
{"level":50,"time":1732831125553,"pid":200797,"hostname":"t14g5-colin","reqId":"req-8","req":{"method":"POST","url":"/gateway/schema","hostname":"localhost:4177","remoteAddress":"127.0.0.1","remotePort":57000},"res":{"statusCode":500},"err":{"type":"TypeError","message":"Cannot convert a BigInt value to a number","stack":"TypeError: Cannot convert a BigInt value to a number\n    at Array.sort (<anonymous>)\n    at buildEntity (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/gateway/node_modules/@azimutt/connector-mariadb/out/mariadb.js:86:14)\n    at /home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/gateway/node_modules/@azimutt/connector-mariadb/out/mariadb.js:34:88\n    at Array.map (<anonymous>)\n    at /home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/gateway/node_modules/@azimutt/connector-mariadb/out/mariadb.js:34:67\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async withConnector (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/gateway/out/routes/index.js:83:16)\n    at async Object.<anonymous> (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/gateway/out/routes/index.js:29:136)"},"msg":"Cannot convert a BigInt value to a number"}
{"level":30,"time":1732831125553,"pid":200797,"hostname":"t14g5-colin","reqId":"req-8","res":{"statusCode":500},"responseTime":120.91904999967664,"msg":"request completed"}
```

Node: v20.18.0
MariaDB: 10.11.10

**Comment by loicknuchel** [comment]
Hi @cdfa 
Thanks for reporting this.
Working on it.
Will let you know when it should be fine.

**Comment by loicknuchel** [comment]
Found the issue and made a fix.
Can you try again with the new CLI version (0.1.34)?
With your `@latest` tag it should update automatically, just run your command again and let me know how it goes.

**Comment by cdfa** [comment]
Wow that was quick!
I get a different error now:
```
{"level":50,"time":1732889186322,"pid":12053,"hostname":"t14g5-colin","reqId":"req-4","req":{"method":"POST","url":"/gateway/schema","hostname":"localhost:4177","remoteAddress":"127.0.0.1","remotePort":56784},"res":{"statusCode":500},"err":{"type":"TypeError","message":"Do not know how to serialize a BigInt","stack":"TypeError: Do not know how to serialize a BigInt\n    at JSON.stringify (<anonymous>)\n    at zodIssueMessageToString (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/models/out/zod.js:50:80)\n    at /home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/models/out/zod.js:36:64\n    at Array.map (<anonymous>)\n    at zodErrorToString (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/models/out/zod.js:31:62)\n    at /home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/models/out/zod.js:8:84\n    at /home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/models/out/zod.js:11:83\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async withConnector (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/gateway/out/routes/index.js:83:16)\n    at async Object.<anonymous> (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/gateway/out/routes/index.js:29:136)"},"msg":"Do not know how to serialize a BigInt"}
{"level":30,"time":1732889186323,"pid":12053,"hostname":"t14g5-colin","reqId":"req-4","res":{"statusCode":500},"responseTime":304.3069469999755,"msg":"request completed"}
```
Progress!

One more note, you may have forgotten to update a version number somewhere:
```
$ npx azimutt@0.1.34 --version
     _            _                       _     _
    / \     ____ (_)  _ __ ___    _   _  | |_  | |_        __ _   _ __    _ __
   / _ \   |_  / | | | '_ ` _ \  | | | | | __| | __|      / _` | | '_ \  | '_ \
  / ___ \   / /  | | | | | | | | | |_| | | |_  | |_   _  | (_| | | |_) | | |_) |
 /_/   \_\ /___| |_| |_| |_| |_|  \__,_|  \__|  \__| (_)  \__,_| | .__/  | .__/
                                                                 |_|     |_|
Version 0.1.32

0.1.32
```

**Comment by loicknuchel** [comment]
Every progress is a win :laughing: 
Arf, too fast to change the correctly the version number :sweat_smile: 
I see the issue, will fix it but not sure I will have the time this afternoon, will let you know when it's done.

**Comment by loicknuchel** [comment]
Hi!
Just made a new version (`0.1.35`), can you try it?
Given it was an error on the error reporting serialization, you may have an other issue after...
Let me know which one it is ^^

**Comment by cdfa** [comment]
Yes, I 'm getting a new error now:
```
{"level":50,"time":1733236961551,"pid":472849,"hostname":"t14g5-colin","reqId":"req-4","req":{"method":"POST","url":"/gateway/schema","hostname":"localhost:4177","remoteAddress":"127.0.0.1","remotePort":50448},"res":{"statusCode":500},"err":{"type":"Error","message":"Invalid Database, 417 issues found in 3 groups:\n- at .entities.?.stats.rows: expect 'number' but got 'bigint' (154) (.entities.0.stats.rows and 13 more)\n- at .entities.?.stats.size: expect 'number' but got 'bigint' (16384) (.entities.0.stats.size and 222 more)\n- at .entities.?.stats.sizeIdx: expect 'number' but got 'bigint' (16384) (.entities.0.stats.sizeIdx and 179 more)","stack":"Error: Invalid Database, 417 issues found in 3 groups:\n- at .entities.?.stats.rows: expect 'number' but got 'bigint' (154) (.entities.0.stats.rows and 13 more)\n- at .entities.?.stats.size: expect 'number' but got 'bigint' (16384) (.entities.0.stats.size and 222 more)\n- at .entities.?.stats.sizeIdx: expect 'number' but got 'bigint' (16384) (.entities.0.stats.sizeIdx and 179 more)\n    at /home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/models/out/zod.js:11:105\n    at ResultFailure.mapError (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/utils/out/result.js:78:34)\n    at /home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/models/out/zod.js:11:91\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async withConnector (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/gateway/out/routes/index.js:83:16)\n    at async Object.<anonymous> (/home/cdfa/.npm/_npx/ea9954d5b4ee9fa6/node_modules/@azimutt/gateway/out/routes/index.js:29:136)"},"msg":"Invalid Database, 417 issues found in 3 groups:\n- at .entities.?.stats.rows: expect 'number' but got 'bigint' (154) (.entities.0.stats.rows and 13 more)\n- at .entities.?.stats.size: expect 'number' but got 'bigint' (16384) (.entities.0.stats.size and 222 more)\n- at .entities.?.stats.sizeIdx: expect 'number' but got 'bigint' (16384) (.entities.0.stats.sizeIdx and 179 more)"}
{"level":30,"time":1733236961552,"pid":472849,"hostname":"t14g5-colin","reqId":"req-4","res":{"statusCode":500},"responseTime":260.54545400105417,"msg":"request completed"}
```

**Comment by loicknuchel** [comment]
Thanks, I see the issue, will fix it this evening and I guess it should be the last one ^^
Sorry for the inconvenience and thanks for your patience :heart:

**Comment by loicknuchel** [comment]
Version `0.1.36` is here :tada: 
I hope this time it will be fine :crossed_fingers:

**Comment by cdfa** [comment]
Sorry was a bit busy with other stuff.
It works great now! Really pretty! :sparkles: 
Thanks :)

**Comment by loicknuchel** [comment]
Yeah! Finally ^^
Sorry for all this trial and error.
Let me know what you think about Azimutt ;)
Cheers!
